### ISSUE TITLE
install "goread"

### ISSUE THREAD

**Issue by dminca** [dminca/nix-config#13]
Make it possible to consume RSS feeds from the terminal with https://github.com/TypicalAM/goread

**Comment by dminca** [comment]
after installing `goread` and setting up my urls, I tried recording a demo with `vhs` but seems it's printing out my keystrokes instead of my interaction in the `goread` app

```yml
categories:
    - name: Cloud Native
      desc: News on Cloud Native tooling
      subscriptions:
        - name: FluxCD Bloga
          desc: News from the FluxCD blog
          url: https://fluxcd.io/blog/index.xml
        - name: External Secrets Operator
          desc: News from the ESO
          url: https://github.com/external-secrets/external-secrets/releases.atom
        - name: Kubernetes Blog
          desc: Kubernetes maintainers blogging
          url: https://kubernetes.io/feed.xml
        - name: NGINX Ingress Controller
          desc: NGINX Ingress Controller GitHub releases
          url: https://github.com/kubernetes/ingress-nginx/releases.atom
        - name: Cert-Manager
          desc: cert-manager operator GitHub releases
          url: https://github.com/cert-manager/cert-manager/releases.atom
    - name: Linux World
      desc: News from the Linux World
      subscriptions:
        - name: NixOS announcements
          desc: Official announcements from the NixOS community
          url: https://nixos.org/blog/announcements-rss.xml

```

https://github.com/user-attachments/assets/fad91e96-6037-4846-899c-e273e9801589

```tape
Output '/Users/dminca/Projects/misc/goread-demo.gif'
Output '/Users/dminca/Projects/misc/goread-demo.mp4'
Output '/Users/dminca/Projects/misc/goread-demo.webm'
Require goread
Require bat

Set Shell zsh
Sleep 1.5s
Type "gorea"
Tab
Escape
Type "[C"
Enter
Sleep 2.5s
Ctrl+R
Type "bat"
Sleep 500ms
Enter
Sleep 6.5s
Type "gorea"
Tab
Enter
Sleep 3s
Enter
Sleep 2s
Enter
Sleep 2s
Enter
Sleep 2s
Escape
Type "[C"
Sleep 500ms
Type "jj"
Sleep 500ms
Type "jjjjjjjjjjjjjjjjjjjjjjjj"
Sleep 3.5s
Type "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj"
Sleep 500ms
Type "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj"
Sleep 500ms
Escape
Type "[D"
Sleep 500ms
Type "j"
Sleep 1s
Enter
Sleep 4.5s
Escape
Type "[Z"
Sleep 500ms
Type "j"
Enter
Sleep 2s
Enter
Sleep 3s
Type "j"
Sleep 10.5s
Type "j"
Sleep 1.5s
Escape
Type "[Z"
Sleep 500ms
Type "j"
Enter
Sleep 1.5s
Enter
Sleep 2s
Type "jk"
Sleep 9.5s
Escape
Type "[Z"
Sleep 1.5s
Escape
Type "[Zj"
Enter
Sleep 500ms
Enter
Sleep 500ms
Enter
Sleep 4.5s
Escape
Type "[C"
Sleep 500ms
Type "jjj"
Sleep 500ms
Type "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj"
Sleep 6.5s
Ctrl+C
```
